export type LoopCategory = "coding" | "content" | "data" | "ops";

export interface Loop {
  slug: string;
  name: string;
  category: LoopCategory;
  goal: string;
  trigger: string;
  discover: string;
  act: string;
  verify: string;
  persist: string;
  exit: string;
  tokensPerCycle: string;
  runtime: "claude-code" | "codex" | "openclaw" | "any";
  runs: string;
  code: string;
  whenToUse?: string;
  requiredTools?: string[];
  humanGates?: string[];
  failureModes?: string[];
  minimumVerifier?: string;
}

export const loops: Loop[] = [
  {
    slug: "content-refresh-loop",
    name: "Content refresh loop",
    category: "content",
    goal: "Pages that lost rank in Search Console are rewritten and re-indexed.",
    trigger: "0 3 * * *",
    discover: "Pull GSC pages whose average position dropped more than 3 in 14 days.",
    act: "Rewrite the page: refresh facts, tighten intro, add missing entities; open a PR.",
    verify: "Meta intact, internal links intact, diff over 25%, build passes.",
    persist: "state.md tracks page, last refresh date, position history.",
    exit: "Queue empty, or a page refreshed twice without rank recovery (escalate to human).",
    tokensPerCycle: "~41k",
    runtime: "claude-code",
    runs: "1.2k runs",
    code: `# crontab
0 3 * * * cd ~/site && claude -p "$(cat loops/content-refresh.md)" --allowedTools "Bash,Edit,Write"`,
  },
  {
    slug: "test-fix-loop",
    name: "Test-fix loop",
    category: "coding",
    goal: "The full test suite passes twice in a row.",
    trigger: "on push",
    discover: "Run the suite; collect every failing test with stack traces.",
    act: "Hand each failure to a subagent scoped to the failing module.",
    verify: "pytest exit 0, twice consecutively (guards against flakes).",
    persist: "Failures log appended to .loop/failures.jsonl for flake analysis.",
    exit: "Two consecutive green runs, or 10 cycles (then open an issue).",
    tokensPerCycle: "~18k",
    runtime: "claude-code",
    runs: "4.7k runs",
    code: `/goal all tests pass and lint is clean -- run the suite, fix the first failure, repeat; stop after 10 turns`,
  },
  {
    slug: "keyword-discovery-loop",
    name: "Keyword discovery loop",
    category: "content",
    goal: "The content queue always holds at least 10 briefed keywords with search demand.",
    trigger: "0 6 * * 1",
    discover: "Diff GSC impression queries against existing pages; crawl competitor sitemaps for gaps.",
    act: "Cluster gaps, score by impressions x absence, draft a one-paragraph brief each.",
    verify: "Each brief has volume evidence and no duplicate against existing slugs.",
    persist: "Briefs appended to queue.md with score and source query.",
    exit: "At least 5 new briefs queued, or no gaps above threshold.",
    tokensPerCycle: "~9k",
    runtime: "any",
    runs: "860 runs",
    code: `0 6 * * 1 cd ~/site && claude -p "$(cat loops/keyword-discovery.md)" --allowedTools "Bash,WebFetch,Write"`,
  },
  {
    slug: "dependency-upgrade-loop",
    name: "Dependency upgrade loop",
    category: "coding",
    goal: "All dependencies are within one minor version of latest, with green CI.",
    trigger: "0 4 * * 6",
    discover: "npm outdated / pip list --outdated; pick the single oldest package.",
    act: "Bump it, run tests, fix breakage within the diff budget.",
    verify: "CI passes and lockfile diff touches only the bumped package tree.",
    persist: "upgrade-log.md records package, from-to, breakage notes.",
    exit: "One package per cycle; loop exits when nothing is outdated.",
    tokensPerCycle: "~22k",
    runtime: "claude-code",
    runs: "2.1k runs",
    code: "/goal `npm outdated` reports zero packages -- bump one package per turn, keep CI green; stop after 8 turns",
  },
  {
    slug: "scrape-validate-loop",
    name: "Scrape-and-validate loop",
    category: "data",
    goal: "Every source is scraped, validated against schema, and loaded.",
    trigger: "*/30 * * * *",
    discover: "Sources list with last-success timestamps; pick stale ones.",
    act: "Fetch, parse, normalize; retry failures with exponential backoff.",
    verify: "Schema validation pass rate at least 98%; row counts within expected band.",
    persist: "Source state table: last_run, last_success, consecutive_failures.",
    exit: "All sources fresh, or a source fails 3x (quarantine and alert).",
    tokensPerCycle: "~6k",
    runtime: "any",
    runs: "9.3k runs",
    code: `*/30 * * * * cd ~/pipeline && claude -p "$(cat loops/scrape-validate.md)" --allowedTools "Bash,Write"`,
  },
  {
    slug: "issue-triage-loop",
    name: "Issue triage loop",
    category: "ops",
    goal: "No issue sits unlabeled for more than 15 minutes during work hours.",
    trigger: "*/15 * * * *",
    discover: "gh issue list with empty label filter, state open.",
    act: "Label by area and priority, dedupe against existing issues, post a one-line summary.",
    verify: "Human spot-checks 1 in 20; mislabel rate must stay under 10%.",
    persist: "Triage decisions appended to .loop/triage.jsonl for calibration.",
    exit: "Queue empty each cycle; loop itself runs indefinitely on cron.",
    tokensPerCycle: "~4k",
    runtime: "claude-code",
    runs: "3.5k runs",
    code: "/schedule every 15 minutes, label new unlabeled issues by area and priority, dedupe, and post a one-line summary on each",
  },
  {
    slug: "ci-failure-fixer-loop",
    name: "CI failure fixer loop",
    category: "coding",
    goal: "The default branch returns to green CI after a failed run.",
    trigger: "on workflow_run failure",
    discover: "Read the latest failed GitHub Actions run, jobs, logs, and touched files.",
    act: "Reproduce the failing command locally, fix the smallest scoped cause, and open a PR.",
    verify: "The failed command passes locally and the same workflow passes on the PR.",
    persist: ".loop/ci-fixes.jsonl records workflow, failing job, root cause, PR, and result.",
    exit: "CI is green, failure is infra-only, or two attempted fixes fail and escalate.",
    tokensPerCycle: "~24k-38k",
    runtime: "codex",
    runs: "seed",
    whenToUse: "Use when CI failures are frequent enough that the first reproduction and small fix should be automated.",
    requiredTools: ["gh CLI", "package manager", "test runner", "git"],
    humanGates: ["Approval before dependency upgrades", "Approval before changing test expectations"],
    failureModes: ["Flaky infra mistaken for code failure", "Over-broad fix touches unrelated modules"],
    minimumVerifier: "The original failing command exits 0 locally.",
    code: `/goal restore green CI -- inspect the latest failed workflow, reproduce the first failing command, fix only the root cause, run the verifier, and open a PR; stop after 2 failed attempts`,
  },
  {
    slug: "pr-review-loop",
    name: "PR review loop",
    category: "coding",
    goal: "Every open PR receives a focused review with blocking issues separated from suggestions.",
    trigger: "*/30 * * * *",
    discover: "List open PRs without an agent review comment in the last 24 hours.",
    act: "Inspect diff, tests, and affected files; post review comments grouped by severity.",
    verify: "Review mentions only changed lines or directly affected behavior, and no duplicate comment exists.",
    persist: ".loop/pr-review.jsonl stores PR number, head SHA, review summary, and comment IDs.",
    exit: "Queue empty, PR is draft, or diff exceeds review budget and escalates.",
    tokensPerCycle: "~12k-28k",
    runtime: "codex",
    runs: "seed",
    whenToUse: "Use for repositories where maintainers need fast first-pass review but still own merge decisions.",
    requiredTools: ["gh CLI", "git", "test output access"],
    humanGates: ["Human decides whether to request changes", "Human approves merge"],
    failureModes: ["Style-only noise", "Reviewing generated files", "Missing broader product context"],
    minimumVerifier: "Every comment maps to a changed file and has a concrete reproduction or rationale.",
    code: `/goal review open PRs -- pick the oldest unreviewed non-draft PR, inspect the diff and checks, post only actionable findings, persist reviewed head SHA, then stop`,
  },
  {
    slug: "stale-pr-cleanup-loop",
    name: "Stale PR cleanup loop",
    category: "ops",
    goal: "No abandoned PR remains open without a next action.",
    trigger: "0 9 * * 1-5",
    discover: "Find PRs with no commits or comments for 14 days.",
    act: "Classify each PR as waiting-author, needs-rebase, superseded, or ready-for-human.",
    verify: "Each PR gets exactly one status comment and label update, with no close action unless policy allows it.",
    persist: ".loop/stale-prs.jsonl records PR, classification, action, and next check date.",
    exit: "All stale PRs have labels/comments, or a PR needs maintainer decision.",
    tokensPerCycle: "~5k-11k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when PR queues grow stale and maintainers need consistent nudges without automatic merges.",
    requiredTools: ["gh CLI", "repo stale policy"],
    humanGates: ["Closing PRs", "Changing branch protection labels"],
    failureModes: ["Comment spam", "Incorrectly marking active work as stale"],
    minimumVerifier: "The PR had no human-visible activity within the configured stale window.",
    code: `0 9 * * 1-5 cd ~/repo && codex exec "label stale PRs, post one concise next-action comment, do not close anything, persist decisions"`,
  },
  {
    slug: "release-notes-loop",
    name: "Release notes loop",
    category: "coding",
    goal: "Every release draft has accurate user-facing notes before tagging.",
    trigger: "on release draft",
    discover: "Diff merged PRs since the last tag and collect labels, commits, and linked issues.",
    act: "Draft grouped release notes: added, changed, fixed, security, migration notes.",
    verify: "Every listed item maps to a merged PR or commit, and breaking changes are explicitly called out.",
    persist: ".loop/release-notes.json stores last tag, draft release ID, and included PRs.",
    exit: "Draft updated, no merged changes exist, or missing product context requires human edit.",
    tokensPerCycle: "~10k-18k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when releases are frequent and changelog quality suffers from manual catch-up.",
    requiredTools: ["gh CLI", "git tags", "release draft access"],
    humanGates: ["Publishing the release", "Writing marketing claims"],
    failureModes: ["Internal refactors presented as user-facing", "Missing migration risks"],
    minimumVerifier: "Every note links back to an included PR, issue, or commit.",
    code: `/goal update release draft notes -- collect merged PRs since latest tag, write grouped user-facing notes, verify every bullet has a source, then stop`,
  },
  {
    slug: "changelog-drafting-loop",
    name: "Changelog drafting loop",
    category: "coding",
    goal: "CHANGELOG.md stays current with merged user-visible changes.",
    trigger: "0 16 * * 5",
    discover: "Read merged PRs from the week that are not represented in CHANGELOG.md.",
    act: "Append concise bullets under Unreleased using existing changelog style.",
    verify: "No duplicate bullets, links resolve, and all bullets map to merged PRs.",
    persist: ".loop/changelog.jsonl records PRs already considered.",
    exit: "No eligible PRs remain, or changelog format is ambiguous.",
    tokensPerCycle: "~6k-12k",
    runtime: "codex",
    runs: "seed",
    whenToUse: "Use for projects with regular small releases and a human-owned final release process.",
    requiredTools: ["git", "gh CLI"],
    humanGates: ["Release version cut", "Breaking-change wording"],
    failureModes: ["Including internal-only work", "Duplicate changelog entries"],
    minimumVerifier: "Each new bullet has a PR reference and no duplicate in the file.",
    code: `/goal keep CHANGELOG.md current -- find merged PRs missing from Unreleased, append concise bullets in existing style, verify links and duplicates, open a PR`,
  },
  {
    slug: "docs-refresh-loop",
    name: "Docs refresh loop",
    category: "content",
    goal: "Docs pages touched by product changes are updated before users hit stale instructions.",
    trigger: "on merged PR with docs-impact label",
    discover: "Find changed code paths, docs-impact labels, and related existing docs pages.",
    act: "Update affected docs with current commands, screenshots notes, and migration caveats.",
    verify: "Docs build passes, code snippets compile or lint, and changed pages link to the relevant feature.",
    persist: ".loop/docs-refresh.jsonl tracks PR, pages checked, updated pages, and verifier result.",
    exit: "Docs updated, no docs page applies, or product owner context is required.",
    tokensPerCycle: "~14k-26k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when product changes often ship before docs are refreshed.",
    requiredTools: ["docs build", "git", "link checker"],
    humanGates: ["Screenshots requiring product access", "Policy or pricing wording"],
    failureModes: ["Docs become too verbose", "Snippet drift when verifier is weak"],
    minimumVerifier: "Docs build passes and touched snippets are checked.",
    code: `/goal refresh docs for docs-impact PRs -- map changed behavior to docs, update only stale instructions, run docs build and link checks, then open a PR`,
  },
  {
    slug: "security-dependency-loop",
    name: "Security dependency loop",
    category: "coding",
    goal: "Known dependency vulnerabilities are patched without broad upgrade churn.",
    trigger: "0 5 * * *",
    discover: "Read npm audit, pip-audit, Dependabot alerts, or advisory feed and pick the highest severity fixable item.",
    act: "Upgrade the minimum package range needed, adjust code only for required breaking changes.",
    verify: "Audit no longer reports the advisory and the test suite passes.",
    persist: ".loop/security-upgrades.jsonl records advisory, package, old/new versions, tests, and PR.",
    exit: "One advisory fixed, no fix is available, or upgrade requires product decision.",
    tokensPerCycle: "~16k-32k",
    runtime: "codex",
    runs: "seed",
    whenToUse: "Use where security patches should move quickly but still be reviewable.",
    requiredTools: ["package manager", "audit tool", "test suite"],
    humanGates: ["Major version upgrades", "Risk acceptance when no patch exists"],
    failureModes: ["Lockfile churn", "Silent transitive breakage"],
    minimumVerifier: "The advisory disappears from audit output and tests pass.",
    code: `/goal fix one dependency advisory -- pick highest severity fixable alert, apply the smallest upgrade, run audit and tests, open a PR, then stop`,
  },
  {
    slug: "flaky-test-quarantine-loop",
    name: "Flaky test quarantine loop",
    category: "coding",
    goal: "Recurring flaky tests are identified with evidence and quarantined only under policy.",
    trigger: "0 */4 * * *",
    discover: "Aggregate recent CI failures by test name, error signature, branch, and retry outcome.",
    act: "Open an issue with evidence or apply the project's quarantine marker if threshold is met.",
    verify: "The failure recurs across at least three independent runs and passes on retry or alternate run.",
    persist: ".loop/flakes.jsonl stores test, signatures, run IDs, confidence, and action.",
    exit: "No test crosses threshold, issue opened, quarantine PR opened, or owner approval needed.",
    tokensPerCycle: "~8k-16k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when flakes waste CI time but automatic quarantine needs strict evidence.",
    requiredTools: ["CI logs", "test history", "gh CLI"],
    humanGates: ["Quarantine without owner policy", "Deleting or weakening tests"],
    failureModes: ["Real regression mislabeled as flake", "Quarantines pile up without repair"],
    minimumVerifier: "The same test/signature failed in three separate runs and passed in at least one retry.",
    code: `/goal identify flaky tests -- aggregate recent CI failures, require repeated signatures, open issue or quarantine PR only when policy threshold is met`,
  },
  {
    slug: "screenshot-qa-loop",
    name: "Screenshot QA loop",
    category: "coding",
    goal: "Important pages render without blank states, overlap, or responsive layout regressions.",
    trigger: "on UI PR",
    discover: "Read changed routes/components and select desktop and mobile viewport screenshots.",
    act: "Run Playwright screenshots, inspect visual diffs, and fix obvious layout regressions.",
    verify: "Screenshots are nonblank, core UI is visible, and text does not overlap at target viewports.",
    persist: ".loop/screenshot-qa.jsonl records route, viewport, screenshot path, findings, and fixes.",
    exit: "All target screenshots pass, visual diff requires design decision, or viewport is unreachable.",
    tokensPerCycle: "~12k-24k",
    runtime: "codex",
    runs: "seed",
    whenToUse: "Use for frontend projects where automated tests miss visual regressions.",
    requiredTools: ["Playwright", "local dev server", "screenshot storage"],
    humanGates: ["Visual redesign choices", "Brand-sensitive imagery"],
    failureModes: ["False positives from animations", "Auth-gated routes skipped"],
    minimumVerifier: "A screenshot exists for each target viewport and contains nonblank main content.",
    code: `/goal visual QA changed routes -- run local app, capture desktop and mobile screenshots, fix obvious overlap/blank states, persist evidence, then stop`,
  },
  {
    slug: "broken-link-repair-loop",
    name: "Broken-link repair loop",
    category: "content",
    goal: "Internal and important external links return valid destinations.",
    trigger: "0 2 * * 0",
    discover: "Crawl sitemap URLs and collect 4xx, 5xx, redirect chains, and missing anchors.",
    act: "Repair internal links, replace dead external citations, or add redirects when policy allows.",
    verify: "The link checker returns zero internal broken links and no priority external dead links.",
    persist: ".loop/link-check.jsonl stores source URL, broken target, fix, and verifier output.",
    exit: "All priority broken links fixed, redirect decision needed, or external replacement is ambiguous.",
    tokensPerCycle: "~7k-15k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use for content sites and docs where broken links directly hurt trust and crawl quality.",
    requiredTools: ["sitemap", "link checker", "git"],
    humanGates: ["301 redirect decisions", "Replacing cited sources in sensitive content"],
    failureModes: ["Temporary network failures", "Replacing authoritative sources with weak ones"],
    minimumVerifier: "A second link-check pass confirms the fixed URLs no longer fail.",
    code: `0 2 * * 0 cd ~/site && codex exec "crawl sitemap, fix internal broken links, replace priority dead external links with cited alternatives, verify, open a PR"`,
  },
  {
    slug: "search-console-striking-distance-loop",
    name: "Search Console striking-distance loop",
    category: "content",
    goal: "Queries ranking positions 8-20 are queued with the next concrete page action.",
    trigger: "0 6 * * 1",
    discover: "Pull GSC query+page rows for the last 28 days and score opportunities by impressions, position, and CTR gap.",
    act: "Create or update a task queue with page, query, opportunity score, and recommended content/internal-link action.",
    verify: "Every queued item has one target URL, one primary query, and no duplicate in-flight PR.",
    persist: "tasks.md and domains/<domain>/todo.md store queued action and follow-up date.",
    exit: "Top N actionable items are queued, GSC permission fails, or every candidate is @human.",
    tokensPerCycle: "~5k-10k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when existing rankings need systematic page-two to page-one recovery.",
    requiredTools: ["Google Search Console API", "domain registry", "git"],
    humanGates: ["Title/meta changes", "Backlinks", "301 decisions"],
    failureModes: ["GSC permissions missing", "Keyword cannibalization ignored"],
    minimumVerifier: "Each queued row has query, URL, position, impressions, score, and an action.",
    code: `0 6 * * 1 cd ~/seo-ops && python3 scripts/codex_screen.py --dry-run && python3 scripts/codex_screen.py`,
  },
  {
    slug: "landing-page-ab-copy-loop",
    name: "Landing-page A/B copy loop",
    category: "content",
    goal: "Low-performing landing page copy variants are replaced with measured alternatives.",
    trigger: "0 7 * * 1",
    discover: "Read analytics, conversion events, page queries, and current copy blocks for eligible pages.",
    act: "Draft one alternative headline, CTA, FAQ, or proof block while preserving protected metadata.",
    verify: "No title/meta changes, build passes, copy maps to the same search intent, and experiment event is configured.",
    persist: ".loop/copy-tests.jsonl stores page, hypothesis, changed block, metric, and start date.",
    exit: "One experiment PR opened, no page meets threshold, or product claim needs approval.",
    tokensPerCycle: "~10k-20k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use for pages with impressions or traffic but weak engagement or conversion.",
    requiredTools: ["analytics", "repo", "build command"],
    humanGates: ["Pricing claims", "Compliance claims", "Title/meta changes"],
    failureModes: ["Changing too many variables", "SEO intent drift"],
    minimumVerifier: "Only one testable copy region changed and the page still builds.",
    code: `/goal propose one landing-page copy experiment -- choose one underperforming page, change one block, preserve title/meta, verify build, persist hypothesis, open a PR`,
  },
  {
    slug: "support-ticket-triage-loop",
    name: "Support-ticket triage loop",
    category: "ops",
    goal: "New support tickets are classified, deduped, and routed within the SLA window.",
    trigger: "*/10 * * * *",
    discover: "Fetch untriaged tickets from the support queue and recent related issues.",
    act: "Classify intent, severity, product area, duplicate status, and draft a concise internal summary.",
    verify: "Ticket has exactly one severity, one owner group, and either duplicate link or next action.",
    persist: ".loop/support-triage.jsonl stores ticket ID, classification, confidence, and action.",
    exit: "Queue empty, confidence below threshold, or customer-impacting escalation needed.",
    tokensPerCycle: "~3k-8k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when support queues need fast routing but responses remain human-owned.",
    requiredTools: ["support API", "issue tracker", "routing rules"],
    humanGates: ["Customer-facing replies", "Refunds or legal issues"],
    failureModes: ["Incorrect severity", "Sensitive data copied into logs"],
    minimumVerifier: "The ticket has a valid queue, severity, owner, and next action.",
    code: `*/10 * * * * codex exec "triage unassigned support tickets, dedupe against known issues, add internal summary and owner, do not send customer replies"`,
  },
  {
    slug: "issue-dedupe-loop",
    name: "Issue dedupe loop",
    category: "ops",
    goal: "Duplicate issues are linked to canonical issues before maintainers spend review time.",
    trigger: "*/20 * * * *",
    discover: "List new issues and search recent open/closed issues by title, stack trace, labels, and keywords.",
    act: "Comment with likely canonical issue, apply duplicate-candidate label, and link evidence.",
    verify: "Similarity score passes threshold and evidence includes at least two matching signals.",
    persist: ".loop/issue-dedupe.jsonl records issue, candidate, score, signals, and comment ID.",
    exit: "Queue empty, duplicate candidate labeled, or confidence below threshold.",
    tokensPerCycle: "~4k-9k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use in active repos where duplicate reports create triage drag.",
    requiredTools: ["gh CLI", "issue search"],
    humanGates: ["Closing issues", "Locking discussions"],
    failureModes: ["Over-linking loosely related reports", "Missing privacy-sensitive attachments"],
    minimumVerifier: "The candidate duplicate shares two concrete signals with the new issue.",
    code: `/schedule every 20 minutes, find new issues, search likely duplicates, label duplicate-candidate only above threshold, comment with evidence, never close automatically`,
  },
  {
    slug: "codex-loop-plugin-audit-loop",
    name: "Codex loop plugin audit loop",
    category: "coding",
    goal: "A repository has a reviewed loop automation proposal before recurring Codex work runs.",
    trigger: "manual before enabling automation",
    discover: "Inspect repo scripts, tests, CI, docs, and existing automation files such as .loop/loop.yaml.",
    act: "Draft or update a loop spec that defines trigger, tool permissions, verifier, state, and exit policy.",
    verify: "The proposed loop references real commands and includes a non-human verifier plus stop condition.",
    persist: ".loop/audit.md stores the proposed loop, risks, required approvals, and owner.",
    exit: "Audit file is complete, no safe verifier exists, or repository owner rejects automation.",
    tokensPerCycle: "~9k-17k",
    runtime: "codex",
    runs: "seed",
    whenToUse: "Use before installing or enabling a Codex loop plugin in a repository.",
    requiredTools: ["git", "test command discovery", "repo docs"],
    humanGates: ["Enabling scheduled automation", "Granting write tokens"],
    failureModes: ["Invented commands", "Automation runs without a real stop condition"],
    minimumVerifier: "The audit names an existing command that can fail the loop.",
    code: `/goal audit this repo for safe Codex loops -- inspect commands and CI, draft .loop/audit.md with trigger, verifier, state, exit, tool permissions, and risks; do not enable automation`,
  },
  {
    slug: "loop-yaml-bootstrap-loop",
    name: "Loop YAML bootstrap loop",
    category: "coding",
    goal: "A repository gains a minimal .loop/loop.yaml that describes one safe recurring workflow.",
    trigger: "manual scaffold",
    discover: "Read package scripts, CI workflows, README, and common maintenance pain points.",
    act: "Create .loop/loop.yaml with one conservative loop definition and comments for required approvals.",
    verify: "YAML parses, referenced commands exist, and verifier command exits 0 on the current repo.",
    persist: ".loop/loop.yaml is committed with the loop definition.",
    exit: "Valid loop.yaml exists, verifier is missing, or owner must decide the workflow.",
    tokensPerCycle: "~6k-12k",
    runtime: "codex",
    runs: "seed",
    whenToUse: "Use when a team wants to start loop engineering but needs a concrete first config.",
    requiredTools: ["git", "YAML parser", "package scripts"],
    humanGates: ["First scheduled run", "Write permissions"],
    failureModes: ["Config points to non-existent commands", "Too many workflows in the first file"],
    minimumVerifier: "The YAML validates and the referenced verifier command exists.",
    code: `/goal create a minimal .loop/loop.yaml -- inspect repo commands, choose one safe maintenance loop, write config, validate YAML and verifier command, then stop`,
  },
  {
    slug: "agent-state-machine-loop",
    name: "Agent state-machine loop",
    category: "coding",
    goal: "An agent workflow runs through explicit states instead of an unbounded while loop.",
    trigger: "event or cron",
    discover: "Load persisted state and observe the current system condition.",
    act: "Transition through observe, plan, act, verify, persist, and terminal states using explicit guards.",
    verify: "Every transition has a guard, every terminal state is reachable, and invalid state fails closed.",
    persist: ".loop/state.json stores state, transition history, last verifier result, and retry count.",
    exit: "Terminal success, terminal failure, max retries, or human approval state.",
    tokensPerCycle: "~8k-18k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when the loop has multiple phases and unbounded retries would be risky.",
    requiredTools: ["state store", "transition validator", "verifier command"],
    humanGates: ["Approval state transitions", "Retry budget increases"],
    failureModes: ["State corruption", "Missing terminal transition", "Retry loop without progress"],
    minimumVerifier: "A transition table check proves every nonterminal state has a guarded next step.",
    code: `/goal run this task as a state machine -- load .loop/state.json, choose the next guarded transition, act once, verify, persist state, stop on terminal or approval-required state`,
  },
  {
    slug: "desired-state-controller-loop",
    name: "Desired-state controller loop",
    category: "ops",
    goal: "Observed system state converges toward a declared desired state without manual babysitting.",
    trigger: "*/15 * * * *",
    discover: "Read desired spec and observed status from APIs, files, or dashboards.",
    act: "Compute drift, apply the smallest allowed actuator action, and record the reconciliation.",
    verify: "Observed status moves closer to desired state and no forbidden field changed.",
    persist: ".loop/controller.jsonl records spec hash, observed status, action, and verifier result.",
    exit: "Observed matches desired, drift is forbidden, actuator fails twice, or human approval is needed.",
    tokensPerCycle: "~7k-14k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use for operational workflows that look like Kubernetes-style reconciliation.",
    requiredTools: ["desired spec", "status API", "actuator command", "policy file"],
    humanGates: ["Destructive actuator actions", "Spec changes"],
    failureModes: ["Controller fights a human change", "Actuator mutates forbidden fields"],
    minimumVerifier: "A status diff shows the action reduced drift or stopped safely.",
    code: `*/15 * * * * codex exec "read desired spec and observed status, reconcile one allowed drift item, verify status moved closer, persist result, stop on forbidden drift"`,
  },
  {
    slug: "scheduled-claude-code-maintenance-loop",
    name: "Scheduled Claude Code maintenance loop",
    category: "coding",
    goal: "A recurring maintenance task runs with the right trigger style for its environment.",
    trigger: "cron, /schedule, /loop, or GitHub Actions",
    discover: "Classify the task by required machine access, session continuity, secrets, and repository event source.",
    act: "Pick the trigger style, write the loop command, and document required permissions.",
    verify: "The selected trigger can reach required files/secrets and runs the verifier command.",
    persist: ".loop/schedule.md stores trigger rationale, command, verifier, and rollback step.",
    exit: "Schedule documented, verifier unavailable, or secrets/permissions need human setup.",
    tokensPerCycle: "~5k-11k",
    runtime: "claude-code",
    runs: "seed",
    whenToUse: "Use when deciding whether a Claude Code loop belongs in cron, a session command, or CI.",
    requiredTools: ["Claude Code", "cron or scheduler", "GitHub Actions when event-driven"],
    humanGates: ["Secrets", "Persistent write access", "Production deploy hooks"],
    failureModes: ["Wrong runtime selected", "Secrets unavailable in scheduled environment"],
    minimumVerifier: "The chosen trigger can run the verifier command in the target environment.",
    code: `/goal choose a Claude Code maintenance trigger -- classify environment needs, write the safest schedule command, verify access to files/secrets, document rollback, then stop`,
  },
  {
    slug: "social-content-autopilot-loop",
    name: "Social content autopilot loop",
    category: "content",
    goal: "Social posts are drafted, scored, deduped, and queued without bypassing safety controls.",
    trigger: "0 8,14,20 * * *",
    discover: "Collect approved topics, recent posts, performance data, and platform constraints.",
    act: "Research, draft, score quality, check similarity, and queue posts that pass policy.",
    verify: "Quality score meets threshold, similarity is below limit, links resolve, and kill switch is off.",
    persist: ".loop/social-queue.jsonl stores draft, score, source topic, scheduled time, and approval state.",
    exit: "Daily queue filled, quality threshold fails three times, kill switch is on, or policy approval needed.",
    tokensPerCycle: "~10k-22k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use only for approved content programs where humans own policy and brand guardrails.",
    requiredTools: ["content calendar", "analytics", "similarity checker", "queue API"],
    humanGates: ["New campaign strategy", "Sensitive topics", "Direct posting permissions"],
    failureModes: ["Low-quality repetitive posts", "Policy drift", "Posting during incident windows"],
    minimumVerifier: "Draft passes quality score, similarity threshold, link check, and kill-switch check.",
    code: `0 8,14,20 * * * codex exec "draft approved social posts, score quality, check similarity and links, queue only if kill switch is off; never post directly"`,
  },
  {
    slug: "content-performance-feedback-loop",
    name: "Content performance feedback loop",
    category: "content",
    goal: "Published content gets a measured next action based on performance data.",
    trigger: "0 6 * * 1",
    discover: "Pull page analytics, GSC queries, conversions, and last update date.",
    act: "Classify each page as keep, refresh, consolidate, add internal links, or escalate.",
    verify: "Every action has metric evidence and does not conflict with protected ranking keywords.",
    persist: ".loop/content-feedback.jsonl records URL, metrics, classification, action, and follow-up date.",
    exit: "Top actions queued, data is insufficient, or a title/meta/backlink decision is needed.",
    tokensPerCycle: "~8k-16k",
    runtime: "any",
    runs: "seed",
    whenToUse: "Use when content decisions should follow measured search and engagement data.",
    requiredTools: ["analytics", "GSC", "content inventory"],
    humanGates: ["Title/meta changes", "Consolidation/301", "Backlinks"],
    failureModes: ["Acting on too little data", "Hurting keywords already ranking well"],
    minimumVerifier: "Each recommendation includes metric evidence and a protected-keyword check.",
    code: `0 6 * * 1 codex exec "score content performance, classify top pages, preserve protected keywords, queue measured next actions, escalate title/meta or 301 decisions"`,
  }
];

export const categories: { id: LoopCategory | "all"; label: string }[] = [
  { id: "all", label: "All" },
  { id: "coding", label: "Coding" },
  { id: "content", label: "Content / SEO" },
  { id: "data", label: "Data" },
  { id: "ops", label: "Ops" },
];

export function getLoop(slug: string) {
  return loops.find((l) => l.slug === slug);
}
